services:
  database:
    image: postgres:15-alpine
    container_name: database
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijsrocks
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - database_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    restart: always

  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Bogota
      DB_TYPE: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: wiki
      DB_USER: wikijs
      DB_PASS: wikijsrocks
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - wiki_config:/config
      - wiki_data:/data

volumes:
  database_data:
  wiki_config:
  wiki_data:
